"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.filosofy = exports.history = exports.math = void 0;
var student_1 = require("./student");
var subject_1 = require("./subject");
var teacher_1 = require("./teacher");
var raphael = new student_1.default('Raphael', new Date(1990, 1, 8));
var person = new student_1.default('João', new Date(2000, 11, 8));
console.log(raphael, person);
// person.name = 'jo';
var testsGrades = [6, 9, 8, 7];
var homeworksGrades = [8, 6];
var student = new student_1.default('Estudante', new Date(1990, 2, 3));
student.tests = testsGrades;
student.homeworks = homeworksGrades;
// console.log(student.sumGrades());
// console.log(student.sumAverageGrade());
exports.math = new subject_1.default('Matemática');
exports.history = new subject_1.default('História');
exports.filosofy = new subject_1.default('Fiosofia');
// console.log(math, history, filosofy);
var dirceu = new teacher_1.default('Dirceu', new Date(1939, 9, 22), 4.500, exports.math);
dirceu.admissionDate = new Date(1988, 1, 3);
var maestri = new teacher_1.default('Tenente Maestri', new Date(1968, 4, 19), 9.350, exports.history);
var frango = new teacher_1.default('Professor Frango Borra Botas', new Date(1985, 7, 30), 3000, exports.filosofy);
console.log(dirceu);
console.log(maestri);
console.log(frango);
