"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.filosofy = exports.history = exports.math = void 0;
var evaluation_1 = require("./evaluation");
var evaluationResult_1 = require("./evaluationResult");
var student_1 = require("./student");
var subject_1 = require("./subject");
var teacher_1 = require("./teacher");
var raphael = new student_1.default('Raphael', new Date(1990, 1, 8));
var joao = new student_1.default('João', new Date(2000, 11, 8));
// console.log(raphael, person);
// person.name = 'jo';
var student = new student_1.default('Estudante', new Date(1990, 2, 3));
// student.tests = testsGrades;
// student.homeworks = homeworksGrades;
// console.log(student.sumGrades());
// console.log(student.sumAverageGrade());
exports.math = new subject_1.default('Matemática');
exports.history = new subject_1.default('História');
exports.filosofy = new subject_1.default('Fiosofia');
// console.log(math, history, filosofy);
var dirceu = new teacher_1.default('Dirceu', new Date(1939, 9, 22), 4.500, exports.math);
dirceu.admissionDate = new Date(1988, 1, 3);
var maestri = new teacher_1.default('Tenente Maestri', new Date(1968, 4, 19), 9.350, exports.history);
var frango = new teacher_1.default('Professor Frango Borra Botas', new Date(1985, 7, 30), 3000, exports.filosofy);
// console.log(dirceu);
// console.log(maestri);
// console.log(frango)
var historyTest1 = new evaluation_1.default(10, maestri, evaluation_1.EvaluationType.TEST);
var historyTest2 = new evaluation_1.default(10, maestri, evaluation_1.EvaluationType.TEST);
var historyTest3 = new evaluation_1.default(10, maestri, evaluation_1.EvaluationType.TEST);
var historyTest4 = new evaluation_1.default(10, maestri, evaluation_1.EvaluationType.TEST);
var historyTest5 = new evaluation_1.default(10, maestri, evaluation_1.EvaluationType.TEST);
// console.log(avaliacao);
var mathHomework1 = new evaluation_1.default(5, dirceu, evaluation_1.EvaluationType.HOMEWORK);
// avalicao1.score = -3;
var raphaelHistory1 = new evaluationResult_1.default(historyTest1, 10);
var raphaelHistory2 = new evaluationResult_1.default(historyTest1, 10);
var raphaelHistory3 = new evaluationResult_1.default(historyTest1, 10);
var raphaelHistory4 = new evaluationResult_1.default(historyTest1, 10);
var raphaelHistory5 = new evaluationResult_1.default(historyTest1, 10);
var raphaelHistory6 = new evaluationResult_1.default(historyTest1, 10);
var raphaelMathHomeworkResult = new evaluationResult_1.default(mathHomework1, 3);
var raphaelHistoryTetsResults = [raphaelHistory1, raphaelHistory2, raphaelHistory3, raphaelHistory4, raphaelMathHomeworkResult];
raphael.addEvaluationResult(raphaelHistory1);
raphael.addEvaluationResult(raphaelHistory2);
raphael.addEvaluationResult(raphaelHistory3);
raphael.addEvaluationResult(raphaelHistory4);
raphael.addEvaluationResult(raphaelHistory5);
// raphael.addEvaluationResult(raphaelHistory6)
console.log(raphael);
