"use strict";
exports.__esModule = true;
var costumer_1 = require("./costumer");
var item_1 = require("./item");
var order_1 = require("./order");
var fritas = new item_1["default"]('Batata frita', 20);
var acai = new item_1["default"]('Açaí', 15);
var coxinha = new item_1["default"]('Coxinha', 5);
var raphael = new costumer_1["default"]('Raphael');
var pedido = new order_1["default"](raphael, [fritas, acai], 'boleto', 0.1);
console.log(pedido.orderWithDiscount());
